affine_trainable: false
auto_save: true
base_fun_name: silu
ckpt_path: ./model
device: cpu
grid: 3
grid_eps: 0.02
grid_range:
- -1
- 1
k: 4
mult_arity: 2
round: 0
sb_trainable: true
sp_trainable: true
state_id: 2
symbolic.funs_name.0:
- - '0'
  - x
  - '0'
  - sin
  - '0'
  - x^2
  - '0'
  - sin
  - sin
  - x
  - '0'
  - '0'
  - x
- - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - '0'
  - x
  - sin
  - x
  - x
  - '0'
  - '0'
  - '0'
- - x
  - sin
  - '0'
  - '0'
  - x
  - '0'
  - x
  - sin
  - '0'
  - sin
  - '0'
  - sin
  - x
symbolic.funs_name.1:
- - '0'
  - '0'
  - sin
- - '0'
  - '0'
  - x
- - '0'
  - '0'
  - '0'
symbolic_enabled: true
width:
- - 13
  - 0
- - 3
  - 0
- - 3
  - 0
